"""MiniWoB++ as a closed-loop task source, scored by the environment's own reward.

Three things make it fit this project without changing the executor:

  * tasks are static HTML served from disk, so the same CDP executor drives them
  * `WOB_REWARD_GLOBAL` / `WOB_DONE_GLOBAL` are set by the task itself, so success
    is decided by the environment and never by the model saying DONE
  * `Math.seedrandom(seed)` before `genProblem()` makes an instance reproducible,
    which is what lets a task id be frozen before any model is run

The supported subset is decided from the action space alone, before any result is
seen, and the coverage is reported rather than quietly applied: tasks needing drag
are out because the executor has no drag, and a task that turns out at run time to
need an unsupported action counts as a failure rather than being dropped.

Vendored HTML: Farama-Foundation/miniwob-plusplus @ 33c3b4d.
"""

import json
import re
from pathlib import Path

# Tasks whose solution requires an action the executor does not implement.
# Determined by reading the task HTML, not by running anything.
UNSUPPORTED = {
    # drag / drop / free mouse movement
    "click-collapsible-2-nodelay", "drag-box", "drag-cube", "drag-items",
    "drag-items-grid", "drag-shapes", "drag-sort-numbers", "resize-textarea",
    "scroll-text", "scroll-text-2", "highlight-text", "highlight-text-2",
    "text-editor", "choose-date-easy", "choose-date-medium", "choose-date-nodelay",
    "copy-paste", "copy-paste-2", "find-midpoint", "number-checkboxes",
    "simple-algebra", "simple-arithmetic", "terminal", "use-slider", "use-slider-2",
    "use-spinner", "visual-addition",
}

# Tasks that need reading an image rather than text. Kept, and labelled, because
# the visual-dependency tier is exactly what this project measures.
VISUAL = {
    "click-shape", "click-color", "count-shape", "identify-shape",
    "grid-coordinate", "click-shades", "visual-addition", "use-colorwheel",
    "use-colorwheel-2", "tic-tac-toe",
}

# The raw reward, not the displayed one. MiniWoB scales some rewards by how much
# of the episode clock is left, so the reported number mixes success with speed.
# Success and latency are reported separately, so the raw value is the one read.
READ_REWARD = (
    "(() => [window.WOB_DONE_GLOBAL === true,"
    " window.WOB_RAW_REWARD_GLOBAL, window.WOB_REWARD_GLOBAL])()"
)
READ_UTTERANCE = "(() => document.getElementById('query')?.innerText ?? '')()"

# `window.onload` only raises a START cover; the problem is generated by
# `startEpisodeReal`. The episode clock is raised from its 10 s default first:
# that default assumes a policy acting in milliseconds, and a VLM taking seconds
# per step would fail every multi-step task on the clock rather than on the task.
# The change is disclosed, and wall-clock time is reported on its own.
START_EPISODE = """((seed, budget) => {
  if (typeof core === 'undefined' || typeof genProblem !== 'function') return ['no-core'];
  core.EPISODE_MAX_TIME = budget;
  if (core.EP_TIMER !== null) { clearTimeout(core.EP_TIMER); core.EP_TIMER = null; }
  try { Math.seedrandom(String(seed)); } catch (e) { return ['no-seedrandom', String(e)]; }
  core.startEpisodeReal();
  return ['ok', core.EPISODE_MAX_TIME, document.querySelectorAll('#area *').length];
})"""


def start_episode(browser, seed, *, budget_ms=600000):
    """Seed the generator, generate the problem, and stretch the episode clock.

    Returns (ok, goal_or_reason). `window.onload` only raises a START cover; the
    problem itself is produced by `startEpisodeReal`.
    """
    expression = f"{START_EPISODE}({json.dumps(seed)}, {int(budget_ms)})"
    try:
        result = browser.evaluate(expression)
    except Exception as exc:
        return False, f"start failed: {type(exc).__name__}"
    if not isinstance(result, list) or not result or result[0] != "ok":
        return False, f"start failed: {result}"
    return True, read_goal(browser)


def available(html_dir):
    """Every task template shipped with the vendored HTML."""
    return sorted(p.stem for p in Path(html_dir).glob("*.html"))


SUBSET = Path(__file__).with_name("miniwob_subset.json")


def supported(html_dir):
    """The subset the executor can act in, frozen before any model was evaluated.

    The static UNSUPPORTED list is not enough on its own: templates like
    `click-shape` draw into a canvas and expose no actionable DOM at all, and
    others expose a single element, which is not a choice. `miniwob_subset.json`
    records what a scan of every template actually found, with the reason each
    exclusion was made. Templates are excluded by what the executor can act in,
    never by how a model scored on them.
    """
    if SUBSET.exists():
        frozen = json.loads(SUBSET.read_text())
        names = set(frozen["templates"])
        return [name for name in available(html_dir) if name in names]
    return [name for name in available(html_dir) if name not in UNSUPPORTED]


def tier(name):
    if name in VISUAL:
        return "visual"
    return "dom"


def family(name):
    """Template family, for split isolation and cluster bootstrap.

    `click-button`, `click-button-sequence` and `click-buttons` share a family:
    resampling them independently would treat near-duplicates as independent
    evidence.
    """
    base = re.sub(r"-(easy|medium|hard|nodelay|delay|\d+)$", "", name)
    return base


def task_url(base_url, name, seed):
    """A MiniWoB page with the episode seeded, so the instance is reproducible."""
    return f"{base_url}/miniwob/{name}.html?seed={seed}"


def build_manifest(html_dir, *, seeds=(0, 1, 2), out=None, limit=None, only=None):
    """The frozen task list: template x seed, with tier and family recorded.

    `only` restricts to an explicit template list -- used to evaluate on the
    families held out of DONE collection, so no template that taught the model
    when to stop is also one it is scored on.
    """
    names = supported(html_dir)
    if only is not None:
        allowed = set(only)
        names = [n for n in names if n in allowed]
    if limit:
        names = names[:limit]
    tasks = []
    for name in names:
        for seed in seeds:
            tasks.append(
                {
                    "task_id": f"{name}#{seed}",
                    "template": name,
                    "seed": seed,
                    "family": family(name),
                    "tier": tier(name),
                }
            )
    frozen = json.loads(SUBSET.read_text()) if SUBSET.exists() else {}
    manifest = {
        "source": "miniwob-plusplus@33c3b4d",
        "subset_frozen": bool(frozen),
        "exclusion_reasons": frozen.get("excluded", {}),
        "templates_available": len(available(html_dir)),
        "templates_supported": len(supported(html_dir)),
        "coverage": len(supported(html_dir)) / max(1, len(available(html_dir))),
        "unsupported_static": sorted(UNSUPPORTED & set(available(html_dir))),
        "seeds": list(seeds),
        "tasks": tasks,
    }
    if out:
        Path(out).write_text(json.dumps(manifest, indent=2))
    return manifest


def read_reward(browser):
    """(done, raw_reward, shown_reward) straight from the task.

    Success is `done and raw_reward > 0`. The model is never consulted: a run
    that claims DONE while the task disagrees is a failure.
    """
    try:
        value = browser.evaluate(READ_REWARD)
    except Exception:
        return False, None, None
    if not isinstance(value, list) or len(value) != 3:
        return False, None, None
    done, raw, shown = value
    return bool(done), raw, shown


def read_goal(browser):
    """MiniWoB states the goal in #query; that is the task instruction."""
    try:
        return (browser.evaluate(READ_UTTERANCE) or "").strip()
    except Exception:
        return ""
